# Generated by Django 6.1.1 on 2026-09-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('is_copyleft', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('summary', models.CharField(max_length=280)),
                ('description', models.TextField(blank=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='catalog.license')),
                ('platforms', models.ManyToManyField(blank=True, related_name='games', to='catalog.platform')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='catalog.tag')),
            ],
            options={
                'ordering': ['-stars', 'title'],
                'indexes': [models.Index(fields=['-stars'], name='catalog_gam_stars_09668b_idx'), models.Index(fields=['title'], name='catalog_gam_title_cb1b3f_idx')],
            },
        ),
    ]
